# @package _group_
#absolute path where models are stored
optim_res: False

models_dir: C:/Users/Jessica/Documents/Proyecto_ssd/SAC/sac_agent/hydra_outputs/

# model_name: "b_gimp_pos_sparse_31-03_15-50_best_eval"
# folder_name: ${test_sac.models_dir}/banana/2021-03-31/15-50-09

model_name: "b_gimp-aff_pos_sparse_31-03_15-52_best_eval"
folder_name: ${test_sac.models_dir}/banana/2021-03-31/15-51-48

eval_cfg:
  n_episodes: 5
  render: False
  print_all_episodes: True
  max_episode_length: 100
  save_images: True