# @package _group_
#absolute path where models are stored
models_dir: C:/Users/Jessica/Documents/Proyecto_ssd/SAC/hydra_outputs/
# model_name: "drawer_best_eval"
# folder_name: ${test_sac.models_dir}/trained_no_img/drawer/

# model_name: "hinge_best_eval"
# folder_name: ${test_sac.models_dir}/trained_no_img/hinge/

# model_name: "slide_best_eval"
# folder_name: ${test_sac.models_dir}/trained_no_img/slide/
folder_name: ${test_sac.models_dir}/best/2021-01-23/12-00-50/
model_name: drawer_x1img_only_r05_23-01_12-00_best_eval

eval_cfg:
  n_episodes: 5
  render: True
  print_all_episodes: True
  max_episode_length: 200
  save_images: True