# @package _group_
#absolute path where models are stored
models_dir: C:/Users/Jessica/Documents/Proyecto_ssd/SAC/hydra_outputs/
# model_name: "drawer_best_eval"
# folder_name: ${test_sac.models_dir}/trained_no_img/drawer/

# model_name: "hinge_best_eval"
# folder_name: ${test_sac.models_dir}/trained_no_img/hinge/

model_name: "slide_best_eval"
folder_name: ${test_sac.models_dir}/trained_no_img/slide/

eval_cfg:
  n_episodes: 5
  render: True
  print_all_episodes: True
  max_episode_length: 200
  save_images: True