# @package _group_
save_dir: "./trained_models"
hyperparameters:
    gamma: 0.99
    actor_lr: 3e-4
    critic_lr: 3e-4
    alpha_lr: 3e-4
    alpha: "auto" #"auto",
    tau: 0.005
    batch_size: 256
    buffer_size: 1e6
    # train_freq: 1 #timesteps collectng data
    # gradient_steps: 1 #timesteps updating gradients
    learning_starts: 100 #timesteps before starting updates

net_cfg:
    hidden_dim: 256
    activation: relu
    use_img: ${img_obs}
    use_depth: False
    use_pos: False

learn_config:
    total_timesteps: 1e6 #millon 1e6
    log_interval: 1400 #log timestep reward every log_interval steps
    max_episode_length: 200 #max episode length
    n_eval_ep: 5