name: Master-Project
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - cudatoolkit=10.1
  - pytorch
  - torchvision
  - pip
  - pillow
  - numpy
  - pip:
    - tqdm
    - pypng
    - Pillow
    - matplotlib
    - ConfigSpace==0.3.10
    - gym==0.17.3
    - hpbandster==0.7.4
    - hydra-colorlog==1.0.0
    - hydra-core==1.0.3
    - numba==0.51.2
    - numpy-quaternion
    - omegaconf==2.0.3
    - opencv-python==4.4.0.44
    - pandas==1.1.3
    - pybullet==3.0.6
    - pyrender==0.1.45
    - python-git==2018.2.1
    - pytorch-lightning==1.1.7
    - scikit-learn==0.23.2
    - scipy==1.6.0
    - segmentation-models-pytorch==0.1.3
    - tacto==0.0.2
    - tensorboard==2.3.0
    - wandb==0.10.24