
max_budget: 300
min_budget: 30
n_iterations: 4
n_workers: 4
run_id: "aff_hpo"
nameserver: "127.0.0.1"

# Write here configuration that is NOT going to be optimized
dataloader:
  num_workers: 4
  pin_memory: True

trainer:
  gpus: 2
  num_nodes: 2
  num_sanity_val_steps: 1