
max_budget: 100
min_budget: 5
n_iterations: 4
n_workers: 1
run_id: "aff_hpo"
nameserver: "127.0.0.1"

# Write here configuration that is NOT going to be optimized
dataloader:
  num_workers: 4
  pin_memory: True

model_cfg:
  model_name: ${model_name}
  loss_weight: [0.2, 0.8]
  optimizer:
    weight_decay: 1e-3

trainer:
  gpus: 1
  num_sanity_val_steps: 1