# @package _group_
max_budget: 250000
min_budget: 50000
n_iterations: 4
n_workers: 2
run_id: "sac_hpo"
nameserver: "127.0.0.1"

hyperparameters: #Hyperparameters that are not optimized
  buffer_size: 1e6
  learning_starts: 200 
  gamma: 0.99

net_cfg:
    hidden_dim: 265
    activation: relu
    
learn_config:
  log_interval: 1400 #log timestep reward every log_interval steps
  max_episode_length: 200 #max episode length
  n_eval_ep: 5

eval_config:
  max_episode_length: 200 
  n_episodes: 5
  render: False
  print_all_episodes: False
  write_file: False

