# @package _group_
hyperparameters:
  gamma: 0.98
  buffer_size: 1e6
  train_freq: 1 #timesteps collectng data
  gradient_steps: 1 #timesteps updating gradients
  learning_starts: 1000 #timesteps before starting updates
  
learn_config:
  log_interval: 1000 #log timestep reward every log_interval steps
  max_episode_length: 200 #max episode length

eval_config:
  max_episode_length: 200 
  n_episodes: 50
  render: False
  print_all_episodes: False
  write_file: False

