
max_budget: 500000
min_budget: 50000
n_iterations: 4
n_workers: 1
run_id: "sac_hpo"
nameserver: "127.0.0.1"

# Write here configuration that is NOT going to be optimized
hyperparameters:
  buffer_size: ${agent.hyperparameters.buffer_size}
  learning_starts: ${agent.hyperparameters.learning_starts} 
  gamma: ${agent.hyperparameters.gamma}

net_cfg:
    activation: relu
    
learn_config:
  log_interval: 1400 #log timestep reward every log_interval steps
  max_episode_length: 200 #max episode length
  n_eval_ep: 5

eval_config:
  max_episode_length: 200 
  n_episodes: 5
  render: False
  print_all_episodes: False
