objects:
  table:
    file: own_objects/modified_table_new_handles/playtable_modified.urdf
    initial_pos: [0.7, 1.0, 0]
    initial_orn: [0, 0, 3.141592653589793]
    fixed: true
    joints:
      top_left_door_joint:
        initial_state: 0  # revolute
      slide_door_joint:
        initial_state: 0  # prismatic
  drawer:
    file: own_objects/drawer/drawer.urdf
    initial_pos: [0.475, 1.0, -0.004]
    initial_orn: [0, 0, 3.141592653589793]
    fixed: true
    joints:
      drawer_joint:
        initial_state: 0  # prismatic