objects:
  table:
    file: table/hightable.urdf
    initial_pos: [0.3, 0.7, 0.02]
    initial_orn: [0, 0, 0]
    fixed: true
  bin:
    file: ais_objects/bin_10_30_50/bin_10_30_50.urdf
    initial_pos: [0.7, 0.75, 0.6]
    initial_orn: [1.57, 0, 0]
    fixed: true
  mug:
    file: 025_mug/google_16k/textured.urdf
    initial_pos: [0.13, 0.7, 0.62]
    initial_orn: [0, 0, 3.141592653589793]
    fixed: false
  orange:
    file: 017_orange/google_16k/textured.urdf
    initial_pos: [0.2, 0.45, 0.62]
    initial_orn: [0, 0, 0]
    fixed: false
  tea:
    file: ais_objects/teayellow/teayellow.urdf
    initial_pos: [0.25, 0.85, 0.63]
    initial_orn: [0, 0, 0]
    fixed: false
  apple:
    file: 013_apple/google_16k/textured.urdf
    initial_pos: [-0.1, 0.6, 0.623]
    initial_orn: [0, 0, 0]
    fixed: false
  banana:
    file: 011_banana/demo/banana_vhacd.urdf
    initial_pos: [0.4, 0.5, 0.61]
    initial_orn: [0, 0, 0]
    fixed: false
  milk:
    file: ais_objects/milk/milk.urdf
    initial_pos: [-0.05, 0.85, 0.63]
    initial_orn: [0, 0, 0]
    fixed: false