# @package _group_
object_files:
  - own_objects/modified_table_new_handles/playtable_modified.urdf
  - own_objects/drawer/drawer.urdf
  - ais_objects/thuna/thuna.urdf
  - 011_banana/demo/banana_vhacd.urdf
  - 024_bowl/google_16k/textured.urdf
  - ais_objects/salt/salt.urdf
  - ais_objects/milk/milk.urdf
  - ais_objects/muesli/muesli.urdf
  - 025_mug/google_16k/textured.urdf
  - ais_objects/sweetener/sweetener.urdf
  - OrgangeMarmelad/meshes/OrangeMarmelade_25k_tex.urdf

object_position:
  - [ 0.7, 1.0, 0 ]  # table
  - [ 0.475, 1.0, -0.004 ]  # drawer
  - [ -0.1, 0.6, 0.54 ]  # thuna
  - [ -0.1, 0.9, 0.63 ]  #banana
  - [ -0.2, 0.65, 0.63 ]  # bowl
  - [ 0.35, 0.9, 0.65 ]  # salt
  - [ 0.06, 0.9, 0.7 ]  # milk
  - [ -0.05, 0.55, 0.7 ]  # muesli
  - [ 0.5, 0.6, 0.63 ]  # mug
  - [ 0.5, 0.89, 0.61 ]  # sweetener
  - [ 0.6, 0.65, 0.65 ]  # marmelade

object_orientation:
  - [ 0, 0, 3.141592653589793 ]  # table
  - [ 0, 0, 3.141592653589793 ]  # drawer
  - [ 0, 0, 0 ]
  - [ 0, 0, 0 ]
  - [ 0, 0, 0 ]
  - [ 0, 0, 0 ]
  - [ 1.5707963267948966, 0, 0 ]  # milk
  - [ 0, 0, 1.5707963267948966 ]  # muesli
  - [ 0, 0, 0 ]
  - [ 0, 0, 0 ]
  - [ 1.5707963267948966, 0, 0 ]  # marmelade

table_ids:
- 0
- 1

scene_joints:  # the names are just for readability, only object_id and joint_index are used to identify it
  left_top_door:
    object_id: 0
    joint_index: 0
    state: 0  # revolute
  slide_door:
    object_id: 0
    joint_index: 3
    state: 0  # prismatic
  drawer:
    object_id: 1
    joint_index: 0
    state: 0  # prismatic

# panda joint values for start positions:
# front left [-48,-43,124,-121,48,140,-92]
# front right [-57.0,-58.0,84.0,-163.0,77.0,121.0,-169.0]