_target_: vr_env.scene.play_table_scene.PlayTableScene
_recursive_: false
data_path: ${data_path}
global_scaling: 0.8
euler_obs: ${robot.euler_obs}
robot_base_position: [0.6, 0.3, 0.5]
robot_base_orientation: [0, 0, 1.5707963]
robot_initial_joint_positions: [-0.30160073570554463, 0.13374573554005056, 0.3231198467624246, -3.0717998184517663, 0.06974993185871471, 3.7525010281742, 0.73030163704711]
surfaces: []
objects:
  fixed_objects:
    table:
      file: own_objects/modified_table_new_handles/playtable_modified.urdf
      initial_pos: [0.7, 1.0, 0]
      initial_orn: [0, 0, 3.141592653589793]
      joints:
        top_left_door_joint:
          initial_state: 0  # revolute
        slide_door_joint:
          initial_state: 0  # prismatic
    drawer:
      file: own_objects/drawer/drawer.urdf
      initial_pos: [0.475, 1.0, -0.004]
      initial_orn: [0, 0, 3.141592653589793]
      joints:
        drawer_joint:
          initial_state: 0  # prismatic