_target_: vr_env.scene.play_table_scene.PlayTableScene
_recursive_: false
data_path: ${data_path}
global_scaling: 0.8
euler_obs: ${robot.euler_obs}
robot_base_position: [0.3, 0.15, 0.6]
robot_base_orientation: [0, 0, 1.5707963]
robot_initial_joint_positions: [-2.353483185958092, 1.6888534743695272, 1.7867690106203291, -2.4913252474417362, -1.4701322596554691, 1.3461304694755656, -2.2195062694339756]
surfaces: []
objects:
  fixed_objects:
    table:
      file: table/hightable.urdf
      initial_pos: [0.3, 0.7, 0.02]
      initial_orn: [0, 0, 0]
    bin:
      file: ais_objects/bin_10_30_50/bin_10_30_50.urdf
      initial_pos: [0.7, 0.75, 0.6]
      initial_orn: [1.57, 0, 0]
  movable_objects:
    hammer_4:
      file: tabletop/hammer_4/hammer_4.urdf
      initial_pos: [0.18, 0.67, 0.614]
      initial_orn: [0, 0, 0]
    plier:
      file: tabletop/plier/plier.urdf
      initial_pos: [0.4, 0.8, 0.607]
      initial_orn: [0, 0, 0]
    screwdriver_2:
      file: tabletop/screwdriver_2/screwdriver_2.urdf
      initial_pos: [0.2, 0.45, 0.61]
      initial_orn: [0, 0, 0]
    screwdriver_3:
      file: tabletop/screwdriver_3/screwdriver_3.urdf
      initial_pos: [0.1, 0.9, 0.614]
      initial_orn: [0, 0, 0]
    screwdriver_4:
      file: tabletop/screwdriver_4/screwdriver_4.urdf
      initial_pos: [-0.1, 0.6, 0.601]
      initial_orn: [0, 0, 0]
    screwdriver_5:
      file: tabletop/screwdriver_5/screwdriver_5.urdf
      initial_pos: [0.4, 0.5, 0.618]
      initial_orn: [0, 0, 0]
    # teapot_3:
    #   file: tabletop/teapot_3/teapot_3.urdf
    #   initial_pos: [-0.15, 0.85, 0.642]
    #   initial_orn: [0, 0, 0]