_target_: vr_env.scene.play_table_scene.PlayTableScene
_recursive_: false
data_path: ${data_path}
global_scaling: 0.8
euler_obs: ${robot.euler_obs}
robot_base_position: [0.3, 0.15, 0.6]
robot_base_orientation: [0, 0, 1.5707963]
robot_initial_joint_positions: [-2.5002145553876627, 1.7627999200228481, 1.652800380838146, -2.3687918139337434, -1.6485854929634876, 1.376110780799737, 0.6374133718338002]
surfaces: []

objects:
  fixed_objects:
    table:
      file: table/hightable.urdf
      initial_pos: [0.3, 0.7, 0.02]
      initial_orn: [0, 0, 0]
      fixed: true
    bin:
      file: ais_objects/bin_10_30_50/bin_10_30_50.urdf
      initial_pos: [0.7, 0.75, 0.6]
      initial_orn: [1.57, 0, 0]
      fixed: true
  movable_objects:
    hammer:
      file: tabletop/hammer/hammer.urdf
      initial_pos: [0.11, 0.88, 0.6146252633582707]
      initial_orn: [0, 0, 3.14]
      fixed: false
    hammer_2:
      file: tabletop/hammer_2/hammer.urdf
      initial_pos: [0.37, 0.91, 0.6120640316496356]
      initial_orn: [0, 0, 0.3]
      fixed: false
    power_drill:
      file: tabletop/power_drill/power_drill.urdf
      initial_pos: [0.42, 0.54, 0.6303941365790483]
      initial_orn: [3.14, 0, -0.4]
      fixed: false
    skillet:
      file: tabletop/skillet/textured.urdf
      initial_pos: [-0.13, 0.58, 0.637398831966368]
      initial_orn: [0, 0, 0.5]
      fixed: false
    teapot:
      file: tabletop/teapot/teapot.urdf
      initial_pos: [-0.11, 0.83, 0.6026503452492561]
      initial_orn: [0, 0, 1.7]
      fixed: false
    # teapot_lid:
    #   file: tabletop/teapot_lid/teapot_lid.urdf
    #   initial_pos: [-0.11, 0.83, 0.6026503452492561]
    #   initial_orn: [0, 0, 0]
    #   fixed: false
    salt:
      file: ais_objects/salt/salt.urdf
      initial_pos: [0.18, 0.58, 0.621952896559465]
      initial_orn: [-1.57, -1.57, 0]
      fixed: false