objects:
  table:
    file: table/hightable.urdf
    initial_pos: [0.3, 0.7, 0.02]
    initial_orn: [0, 0, 0]
    fixed: true
  bin:
    file: ais_objects/bin_10_30_50/bin_10_30_50.urdf
    initial_pos: [0.7, 0.75, 0.6]
    initial_orn: [1.57, 0, 0]
    fixed: true
  frying_pan:
    file: tabletop/frying_pan/frying_pan.urdf
    initial_pos: [0.11, 0.88, 0.6018220029124765]
    initial_orn: [0, 0, -1.54]
    fixed: false
  knife:
    file: tabletop/kitchen_knife/kitchen_knife.urdf
    initial_pos: [0.37, 0.91, 0.6069920607828857]
    initial_orn: [0, 0, 0]
    fixed: false
  bowl:
    file: 024_bowl/google_16k/textured.urdf
    initial_pos: [0.18, 0.58, 0.6230520401985216]
    initial_orn: [0, 0, 0]
    fixed: false
  frying_pan_2:
    file: tabletop/frying_pan_2/frying_pan.urdf
    initial_pos: [-0.13, 0.58, 0.6035380616166205]
    initial_orn: [0, 0, -1]
    fixed: false
  whisk:
    file: tabletop/whisk/whisk.urdf
    initial_pos: [-0.11, 0.83, 0.6156331388887535]
    initial_orn: [0, 0, 0.5]
    fixed: false
  spatula:
    file: tabletop/spatula/spatula.urdf
    initial_pos: [0.42, 0.54, 0.6045897331557224]
    initial_orn: [0, 0, 3.1416]
    fixed: false
