# @package _group_
object_files:
- table/hightable.urdf
- 025_mug/google_16k/textured.urdf
- 029_plate/google_16k/textured.urdf
- 032_knife/google_16k/textured.urdf
- ais_objects/oil/oil.urdf
- 017_orange/google_16k/textured.urdf
- ais_objects/teayellow/teayellow.urdf
- 013_apple/google_16k/textured.urdf
- 011_banana/demo/banana_vhacd.urdf
- ais_objects/milk/milk.urdf

object_position:
- [ 0.3, 0.7, 0.02 ]  # table for scale 0.8
#- [ 0.3, 0.7, 0.08 ]  # table for scale 0.7
- [ 0.13, 0.7, 0.65 ]  # mug
- [ 0.35, 0.92, 0.61 ]  # plate
- [ 0.2125, 0.95, 0.61 ]  # knife
- [ 0.3, 0.56, 0.7 ]  # oil
- [ 0.4875, 0.4, 0.61 ]  # orange
- [ 0.68, 0.8, 0.65 ]  # tea
- [ -0.09, 0.4, 0.61 ]  # apple
- [ 0.8, 0.5, 0.61 ]  # banana
- [ 0.05, 0.85, 0.68 ]  # milk

object_orientation:
- [ 0, 0, 0 ]
- [ 0, 0, 3.141592653589793 ]  # mug
- [ 0, 0, 0 ]
- [ 3.141592653589793, 0, 1.5707963267948966 ]  # knife
- [ 0, 0, 0 ]
- [ 0, 0, 0 ]
- [ 0, 0, 0 ]
- [ 0, 0, 0 ]
- [ 0, 0, 0 ]
- [ 1.5707963267948966, 0, 0 ]  # milk

table_ids:
- 0

scene_joints: {}

# panda joint values for start positions:
# apple [18,47,55,-125,105,219,-170]
# banana [61.0,-104,-93,-105,-103,83,-140]