objects:
  table:
    file: table/hightable.urdf
    initial_pos: [0.3, 0.7, 0.02]
    initial_orn: [0, 0, 0]
    fixed: true
  bin:
    file: ais_objects/bin_20_30_50/bin_20_30_50.urdf
    initial_pos: [0.6, 0.8, 0.6]
    initial_orn: [0, 0, 1.57]
    fixed: true
  meat:
    file: 010_potted_meat_can/google_16k/textured.urdf
    initial_pos: [0.35, 0.92, 0.623]
    initial_orn: [0, 0, 2]
    fixed: false
  beans:
    file: ais_objects/beans/beans.urdf
    initial_pos: [0.2, 0.7, 0.65]
    initial_orn: [0, 0, 0]
    fixed: false
  cup:
    file: 065-a_cups/google_16k/textured.urdf
    initial_pos: [0.15, 0.9, 0.63]
    initial_orn: [0, 0, 0]
    fixed: false
  gelatin:
    file: 009_gelatin_box/google_16k/textured.urdf
    initial_pos: [-0.1, 0.6, 0.623]
    initial_orn: [0, 0, 0]
    fixed: false
  chewinggum:
    file: ais_objects/chewinggum/chewinggum.urdf
    initial_pos: [-0.05, 0.85, 0.63]
    initial_orn: [0, 0, 0]
    fixed: false
  rubic cube:
    file: 077_rubiks_cube/google_16k/textured.urdf
    initial_pos: [0.08, 0.48, 0.623]
    initial_orn: [0, 0, 0]
    fixed: false