objects:
  table:
    file: table/hightable.urdf
    initial_pos: [0.3, 0.7, 0.02]
    initial_orn: [0, 0, 0]
    fixed: true
  bin:
    file: ais_objects/bin_10_30_50/bin_10_30_50.urdf
    initial_pos: [0.7, 0.75, 0.6]
    initial_orn: [1.57, 0, 0]
    fixed: true
  cup:
    file: 065-d_cups/google_16k/textured.urdf
    initial_pos: [0.45, 0.5, 0.64]
    initial_orn: [0, 0, 0]
    fixed: false
  sweetener:
    file: ais_objects/sweetener/sweetener.urdf
    initial_pos: [0.38, 0.8, 0.62]
    initial_orn: [0, 0.8, 0]
    fixed: false
  can:
    file: 002_master_chef_can/google_16k/textured.urdf
    initial_pos: [0.15, 0.9, 0.64]
    initial_orn: [1.57, 0, 0]
    fixed: false
    global_scaling: 0.7
  cleaner:
    file: ais_objects/cleaner/cleaner.urdf
    initial_pos: [-0.1, 0.55, 0.62]
    initial_orn: [1.57, -0.34, 3.14]
    fixed: false
  airplane:
    file: 072-a_toy_airplane/google_16k/textured.urdf
    initial_pos: [0.15, 0.66, 0.62]
    initial_orn: [0, 0, 0]
    global_scaling: 0.4
    fixed: false
  thuna:
    file: 007_tuna_fish_can/google_16k/textured.urdf
    initial_pos: [-0.08, 0.82, 0.62]
    initial_orn: [0, 0, 3.14]
    fixed: false