# @package _group_
train:
  - _target_: torchvision.transforms.Resize
    size: ${env_wrapper.img_size}
  - _target_: affordance_model.utils.transforms.ScaleImageTensor  # Scale 0-255 to 0-1
  - _target_: torchvision.transforms.Normalize
    mean: [0.5,]
    std: [0.5,]
  - _target_: affordance_model.utils.transforms.AddGaussianNoise
    mean: [0.0]
    std: [0.01]
    
validation:
  - _target_: torchvision.transforms.Resize
    size: ${env_wrapper.img_size}
  - _target_: affordance_model.utils.transforms.ScaleImageTensor
  - _target_: torchvision.transforms.Normalize
    mean: [0,]
    std: [1,]