project_path:  /mnt/ssd_shared/Users/Jessica/Documents/Proyecto_ssd/
data_path: ${project_path}/VREnv/data/
save_dir: ./combined/hydra_outputs/${task}
model_name: full
task: pickup
euler_obs: true
img_size: 64
repeat_training: 1

viz_obs: False
# path to load affordance models either gripper_cam 
# or static_cam
models_path: "${project_path}/Master-project/trained_models/"

# Static cam affordance model to detect the targets
target_search_aff:
  model_path: ${models_path}/tabletop_multiscene_static_sideview.ckpt  # static_centers_2-5_1_5_1_200px_epoch_13.ckpt # 
  img_size: 200
  hyperparameters:
    n_classes: 2
    hough_voting:
      skip_pixels: 2
      inlier_threshold: 0.7
      angle_discretization: 100
      inlier_distance: 10
      percentage_threshold: 0.3
      object_center_kernel_radius: 15
    centers_loss:
      weight: 5
    aff_loss:
      weight: 2
      dice_loss:
        add: True
        weight: 5
      ce_loss:
        weight: 1
        class_weights: [0.2, 0.8]
    optimizer:
      lr: 1e-5
      weight_decay: 1e-3
    unet_cfg:
      decoder_channels: [128, 64, 32]

#
target_search: "env"
# Define types of observation input to the RL agent
env_wrapper:
  gripper_cam:
    use_img: True
    use_depth: False
  static_cam:
    use_img: False
    use_depth: False
  use_pos: True
  history_length: 1
  skip_frames: 0
  img_size: ${img_size}
  use_aff_termination: False
  max_target_dist: 0.15

# Affordance configuration for RL agent observation inputs
affordance:
    static_cam:
      use: False
      model_path: ${models_path}/tabletop_multiscene_static_sideview.ckpt
      img_size: 200
      hough_voting:
        skip_pixels: 2
        inlier_threshold: 0.7
        angle_discretization: 100
        inlier_distance: 10
        percentage_threshold: 0.3
        object_center_kernel_radius: 10
      hyperparameters:
        n_classes: 2
        centers_loss:
          weight: 2.5
        aff_loss:
          weight: 1
          dice_loss:
            add: True
            weight: 5
          ce_loss:
            weight: 1
            class_weights: [0.2, 0.8]
        optimizer:
          lr: 1e-5
          weight_decay: 1e-3
        unet_cfg:
          decoder_channels: [128, 64, 32]
    gripper_cam:
      use: False  # Use affordance in observation
      use_distance: False
      densify_reward: False  # Use affordance to shape the reward function
      target_in_obs: False  # Add target detected by affordance into observation
      model_path: ${models_path}/tabletop_multiscene_gripper_labels.ckpt # tabletop_multiscene_gripper_sideview_2.ckpt  # gripper_centers_2-5_1_5_1_64px_epoch_40.ckpt
      hough_voting:
        skip_pixels: 2
        inlier_threshold: 0.7
        angle_discretization: 100
        inlier_distance: 10
        percentage_threshold: 0.3
        object_center_kernel_radius: 10
      hyperparameters:
        n_classes: 2
        centers_loss:
          weight: 2.5
        aff_loss:
          weight: 1
          dice_loss:
            add: True
            weight: 5
          ce_loss:
            weight: 1
            class_weights: [0.2, 0.8]
        optimizer:
          lr: 1e-5
          weight_decay: 1e-3
        unet_cfg:
          decoder_channels: [128, 64, 32]

all_cameras:
  sideview_right: #Side view (slide)
    _target_: vr_env.camera.static_camera.StaticCamera
    name: static_right
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    look_at: [ 0.2, 0.8, 0.6 ]
    look_from: [0.8, 0.2, 1]
  sideview_left: #Side view (drawer)
    _target_: vr_env.camera.static_camera.StaticCamera
    name: static_left
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    look_at: [ 0.05, 0.8, 0.6 ]
    look_from: [-0.5, 0.2, 1]
  topview:    
    _target_: vr_env.camera.static_camera.StaticCamera
    name: static_topview
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    look_at: [ 0.2, 0.85, 0.5 ]
    look_from: [0.2, 0.05, 1.3]
  tabletop_topview:
    _target_: vr_env.camera.static_camera.StaticCamera
    name: tabletop_static
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300  # 200
    height: 300  # 200
    look_at: [0.3, 0.8, 0.5]
    look_from: [0.3, 0.6, 1.5]
    # look_at: [0.2753056585788727, 0.4048122465610504, 0.04299933835864067]
    # look_from: [0.2753049433231638, 1.551965045589526, 1.681303648001446]
  static:
    _target_: vr_env.camera.static_camera.StaticCamera
    name: static
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    look_at: [ 0.1, 0.8, 0.7 ]
    look_from: [ 0.3, -0.2, 1.3 ]
  gripper:
    _target_: vr_env.camera.gripper_camera.GripperCamera
    name: gripper
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
  tabletop_test:
    _target_: vr_env.camera.static_camera.StaticCamera
    name: tidy_up_test
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 760
    height: 760
    look_at: [0.2773292660713196, 0.7766451239585876, 0.20271989703178406]
    look_from: [-0.21922546214082672, 0.22516583397073475, 1.1457490759304818]
  tabletop_multiscene:
    _target_: vr_env.camera.static_camera.StaticCamera
    name: tabletop_multiscene
    fov: 45
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 200
    height: 200
    look_at: [0.22791078686714172, 0.008461681194603443, -0.24000032246112823]
    look_from: [0.22790421545536008, 1.570319612342189, 1.5822541675395883]
  tabletop_sideview:
    _target_: vr_env.camera.static_camera.StaticCamera
    name: tabletop_sideview
    fov: 45
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 200
    height: 200
    look_at: [0.15026406943798065, 0.6811332106590271, 0.46438753604888916]
    look_from: [-0.32631213472589593, 0.6811343431473001, 1.5656936606290373]

hydra:
  run:
    dir: ${save_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - robot: panda_tabletop_longer_finger
  - scene: tabletop_random
  - env: env_combined
  - env@eval_env: env_combined
  - camera_conf: tabletop_sideview
  - agent: default
  - test: test_tabletop
  - transforms@affordance.transforms: aff_transforms
  - transforms@env_wrapper.transforms: rl_transforms
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog