data_dir: C:/Users/Jessica/Documents/Proyecto_ssd/datasets/vrenv_affordance/
save_dir: ./affordance_model/hydra_outputs/

model_name: affordance_unet
n_epochs: 100
img_size: 128 #32x4, will be subsampled 3 times

dataloader:
  num_workers: 2
  batch_size : 4 #28
  pin_memory: True

model_cfg:
  model_name: "${model_name}"
  optimizer:
    lr: 0.0005
    weight_decay: 1e-3

trainer:
  gpus: 1
  max_epochs: 20
  num_sanity_val_steps: 1

project_folder: C:/Users/Jessica/Documents/Proyecto_ssd/SAC/affordance_model

viz:
  data_dir: ${data_dir}/frames
  folder_name: ${project_folder}/hydra_outputs/2021-02-09/00-24-17
  model_name: affordance-epoch=18-val_loss=0.32.ckpt

defaults:
  - image_transforms@dataset.transforms: transforms #Load from folder image_transforms, as dataset.transforms
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

#-- Hydra config --#
hydra:
  run:
    dir: ${save_dir}./${now:%Y-%m-%d}__${now:%H-%M-%S} # Output directory for normal runs
