project_path: C:/Users/Jessica/Documents/Proyecto_ssd
data_path: "${project_path}/VREnv/data/"
save_dir: ./sac_agent/hydra_outputs/${task}
task: slide
model_name: sac_vrenv
repeat_training: 1
euler_obs: True

# Observation wrapper
img_size: 128
use_static_cam: False
use_gripper_cam: False
use_pos: False
use_depth: False

# Environment
rand_init_state: False
sparse_reward: False

env_wrapper:
  use_depth: ${use_depth}
  use_pos: ${use_pos}
  use_static_cam: ${use_static_cam}
  use_gripper_cam: ${use_gripper_cam}
  history_length: 1
  skip_frames: 0
  img_size: ${img_size}
  transforms: ${transforms}


models_path: "${project_path}/SAC/trained_models/"
affordance:
    hyperparameters:
      loss_weight: [0.2, 0.8]
      optimizer:
        lr: 5e-6
        weight_decay: 1e-3
    static_cam:
      use: False
      model_path: ${models_path}/affordance_gripper_16ep_val_loss=0.4135.ckpt
    gripper_cam:
      use: False
      model_path: ${models_path}/affordance_gripper_16ep_grayscale_val_loss=0.3706.ckpt
#Env 
defaults:
  - transforms: img_transforms
  - robot: panda
  - scene: basic_playtable
  - env: env
  - env@eval_env: env
  - camera_conf: topview
  - test_sac: test
  - agent: default
  - optim@optim: config_optim
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

all_cameras:
  sideview_right: #Side view (slide)
    _target_: vr_env.camera.static_camera.StaticCamera
    name: sideview_right
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    look_at: [ 0.2, 0.8, 0.6 ]
    look_from: [0.8, 0.2, 1]
  sideview_left: #Side view (drawer)
    _target_: vr_env.camera.static_camera.StaticCamera
    name: sideview_left
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    look_at: [ 0.05, 0.8, 0.6 ]
    look_from: [-0.5, 0.2, 1]
  topview:    
    _target_: vr_env.camera.static_camera.StaticCamera
    name: topview
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    look_at: [ 0.2, 0.85, 0.5 ]
    look_from: [0.2, 0.05, 1.3]
  static:
    _target_: vr_env.camera.static_camera.StaticCamera
    name: static
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    look_at: [ 0.1, 0.8, 0.7 ]
    look_from: [ 0.3, -0.2, 1.3 ]
  gripper:
    _target_: vr_env.camera.gripper_camera.GripperCamera
    name: gripper
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    gripper_cam_link: 12 # TODO do not hardcode this, use robot property? e.g. ${robot.camera_link_id}

  opposing:
    _target_: vr_env.camera.static_camera.StaticCamera
    name: opposing
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    look_at: [ 0.4, 0.5, 0.6 ]
    look_from: [ 0.4, 1.5, 0.9 ]

hydra:
  run:
    dir: ${save_dir}./${now:%Y-%m-%d}/${now:%H-%M-%S}