#Environment
vrenv_path: C:/Users/Jessica/Documents/Proyecto_ssd/VREnv
vrenv_data_path: C:/Users/Jessica/Documents/Proyecto_ssd/VREnv/data/

#Load agent
models_dir: C:/Users/Jessica/Documents/Proyecto_ssd/SAC/hydra_outputs/
model_name: drawer_best_eval
folder_name: ${models_dir}/trained_no_img/drawer/

#Save dataset
save_dir: "C:/Users/Jessica/Documents/Proyecto_ssd/datasets/vrenv_affordance/"

viz: True
n_episodes: 1
max_timesteps: 150

defaults:
  - agent: sac_default
  - env: env
  - scene@env.scene: basic_playtable
  - camera_conf@env: topview
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

all_cameras:
  sideview_right: #Side view (slide)
    _target_: src.camera.static_camera.StaticCamera
    name: sideview_right
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    look_at: [ 0.2, 0.8, 0.6 ]
    look_from: [0.8, 0.2, 1]
  sideview_left: #Side view (drawer)
    _target_: src.camera.static_camera.StaticCamera
    name: sideview_left
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    look_at: [ 0.05, 0.8, 0.6 ]
    look_from: [-0.5, 0.2, 1]
  topview:    
    _target_: src.camera.static_camera.StaticCamera
    name: topview
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    look_at: [ 0.2, 0.85, 0.5 ]
    look_from: [0.2, 0.05, 1.3]
hydra:
  run:
    dir: ../test_runs/${now:%Y-%m-%d}/${now:%H-%M-%S}