#Environment
output_size:
  static: 300
  gripper: 96
mask_on_close: True
save_viz: True
euler_obs: True
frames_before_saving: 300
# For collecting dataset with playdata
folder_name: task_A_A
play_data_dir: ${path.datasets}/unprocessed/${folder_name}

#Output directory where dataset will be stored
output_dir: ${path.datasets}/${folder_name}/
viz: True
split_dataset: True
data_split: "train"  # Where to write the data if previous is false
hydra:
  run:
    dir: ./hydra_outputs/datacollection/${now:%Y-%m-%d}_${now:%H-%M-%S}

use_vr: false
defaults:
  - labeling: simulation
  - env: env_labeling
  - robot: panda
  - scene: tabletop_1
  - paths: general_paths
  - camera_conf@cameras: no_cameras
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog