#Environment
project_path: /mnt/ssd_shared/Users/Jessica/Documents/Thesis_ssd/
data_path: ${project_path}/VREnv/data/

output_size:
  static: 300
  gripper: 96
mask_on_close: True
save_viz: True
euler_obs: True
frames_before_saving: 300
# For collecting dataset with playdata
folder_name: drawer_affordance
play_data_dir: ${project_path}/datasets/rendered_data/${folder_name}

#Output directory where dataset will be stored
output_dir: ${project_path}/datasets/${folder_name}/
viz: True
split_dataset: True
data_split: "train"  # Where to write the data if previous is false
hydra:
  run:
    dir: ./hydra_outputs/datacollection/${now:%Y-%m-%d}_${now:%H-%M-%S}

use_vr: false
defaults:
  - labeling: simulation
  - env: env_labeling
  - robot: panda
  - scene: tabletop_1
  - camera_conf@cameras: no_cameras
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog