project_path: /mnt/ssd_shared/Users/Jessica/Documents/Thesis_ssd
data_dir: ${project_path}/datasets/teleop_real/drawer/2021-11-18
save_dir: ./hydra_outputs/affordance_model/

model_name: test
n_epochs: 100
img_size:
  static: 200
  gripper: 84

rand_crop: 0.8

dataset:
  root_dir: ${data_dir}
  cam: static
  n_train_ep: -1  # Train using all episodes
  radius:
    static: 14
    gripper: 13

dataloader:
  num_workers: 4
  batch_size : 128 #28
  pin_memory: True

model_cfg:
  model_name: ${model_name}
  n_classes: 2
  hough_voting:
    skip_pixels: 5
    inlier_threshold: 0.6
    angle_discretization: 100
    inlier_distance: 10
    percentage_threshold: 0.3
    object_center_kernel_radius: 10
  centers_loss:
    weight: 2.5
  aff_loss:
    weight: 1
    dice_loss:
      add: True
      weight: 5
    ce_loss:
      weight: 1
      class_weights: [0.2, 0.8]
  optimizer:
    lr: 1e-5
    weight_decay: 1e-4
  unet_cfg:
    decoder_channels: [128, 64, 32]

trainer:
  gpus: 1
  max_epochs: ${n_epochs}
  num_sanity_val_steps: 1

#-- Hydra config --#
hydra:
  run:
    dir: ${save_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S} # Output directory for normal runs

defaults:
  - optim: aff_optim
  - transforms@dataset.transforms_cfg: aff_transforms
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
