data_dir:  C:/Users/Jessica/Documents/Proyecto_ssd/datasets/vrenv_play_large_handles/
save_dir: ./affordance_model/hydra_outputs/

model_name: gripper_1CE_5dice
n_epochs: 40
img_size: 64

dataset:
  root_dir: ${data_dir}
  cam: gripper
  n_train_ep: 16 # n-1 training ep, n_episodes in [8,6,4]

dataloader:
  num_workers: 4
  batch_size : 128 #28
  pin_memory: True

model_cfg:
  model_name: "${model_name}"
  n_classes: 2
  dice_loss:
    add: True
    weight: 5
  ce_loss:
    weight: 1
    class_weights: [0.2, 0.8]
  optimizer:
    lr: 1e-5
    weight_decay: 1e-3
  unet_cfg:
    decoder_channels: [256, 128, 64, 32]

trainer:
  gpus: 1
  max_epochs: ${n_epochs}
  num_sanity_val_steps: 1

defaults:
  - optim: aff_optim
  - transforms@dataset.transforms: img_transforms #Load from folder image_transforms, as dataset.transforms
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

#-- Hydra config --#
hydra:
  run:
    dir: ${save_dir}./${now:%Y-%m-%d}/${now:%H-%M-%S} # Output directory for normal runs
