save_dir: ./hydra_outputs/affordance_model/

model_name: test
n_epochs: 50
img_size:
  static: 200
  gripper: 64
  all: 100  # Resize to this if using all images

rand_crop: 0.8

dataset_name: task_A_A
dataset:
  root_dir: ${paths.datasets}/${dataset_name}
  cam: static
  n_train_ep: -1  # Train using all episodes
  radius:
    static: 14
    gripper: 10

dataloader:
  num_workers: 4
  batch_size : 128 #28
  pin_memory: True

model_cfg:
  model_name: ${model_name}
  n_classes: 2
  hough_voting:
    skip_pixels: 5
    inlier_threshold: 0.6
    angle_discretization: 100
    inlier_distance: 10
    percentage_threshold: 0.3
    object_center_kernel_radius: 10
  centers_loss:
    weight: 2.5
  aff_loss:
    weight: 1
    dice_loss:
      add: True
      weight: 5
    ce_loss:
      weight: 1
      class_weights: [0.2, 0.8]
  optimizer:
    lr: 1e-5
    # weight_decay: 1e-4
  unet_cfg:
    decoder_channels: [128, 64, 32]

trainer:
  gpus: -1
  max_epochs: ${n_epochs}
  num_sanity_val_steps: 1
  strategy: ddp

#-- Hydra config --#
hydra:
  run:
    dir: ${save_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S} # Output directory for normal runs

defaults:
  - paths: general_paths
  - transforms@dataset.transforms_cfg: aff_transforms
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
