project_path: C:/Users/Jessica/Documents/Proyecto_ssd
data_path: "${project_path}/VREnv/data/"
save_dir: ./sac_agent/hydra_outputs/${task}
task: slide
model_name: sac_vrenv
repeat_training: 1
euler_obs: True
init_pos_near: False

# Observation wrapper
img_size: 64
use_static_cam: False
use_gripper_cam: False
use_pos: False
use_depth: False

# Environment
sparse_reward: False

env_wrapper:
  use_depth: ${use_depth}
  use_pos: ${use_pos}
  use_static_cam: ${use_static_cam}
  use_gripper_cam: ${use_gripper_cam}
  history_length: 1
  skip_frames: 0
  img_size: ${img_size}
  transforms: ${transforms}


models_path: "${project_path}/SAC/trained_models/"
affordance:
    hyperparameters:
      n_classes: 2
      dice_loss:
        add: True
        weight: 5
      ce_loss:
        weight: 1
        class_weights: [0.2, 0.8]
      optimizer:
        lr: 1e-5
        weight_decay: 1e-3
    static_cam:
      use: False
      model_path: ${models_path}/affordance_gripper_16ep_val_loss=0.4135.ckpt
    gripper_cam:
      use: False
      model_path: ${models_path}/gripper_1CE_5dice_64px_miou=0.629.ckpt

all_cameras:
  sideview_right: #Side view (slide)
    _target_: vr_env.camera.static_camera.StaticCamera
    name: static_right
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    look_at: [ 0.2, 0.8, 0.6 ]
    look_from: [0.8, 0.2, 1]
  sideview_left: #Side view (drawer)
    _target_: vr_env.camera.static_camera.StaticCamera
    name: static_left
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    look_at: [ 0.05, 0.8, 0.6 ]
    look_from: [-0.5, 0.2, 1]
  topview:    
    _target_: vr_env.camera.static_camera.StaticCamera
    name: static_topview
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    look_at: [ 0.2, 0.85, 0.5 ]
    look_from: [0.2, 0.05, 1.3]
  tabletop_topview:
    _target_: vr_env.camera.static_camera.StaticCamera
    name: tabletop_topview
    fov: 45
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 200
    height: 200
    look_at: [0.2753056585788727, 0.4048122465610504, 0.04299933835864067]
    look_from: [0.2753049433231638, 1.551965045589526, 1.681303648001446]
  static:
    _target_: vr_env.camera.static_camera.StaticCamera
    name: static
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    look_at: [ 0.1, 0.8, 0.7 ]
    look_from: [ 0.3, -0.2, 1.3 ]
  gripper:
    _target_: vr_env.camera.gripper_camera.GripperCamera
    name: gripper
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
  tabletop_test:
    _target_: vr_env.camera.static_camera.StaticCamera
    name: tidy_up_test
    fov: 45
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 200
    height: 200
    look_at: [0.2753056585788727, 0.4048122465610504, 0.04299933835864067]
    look_from: [0.2753049433231638, 1.551965045589526, 1.681303648001446]

hydra:
  run:
    dir: ${save_dir}./${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - transforms: rl_transforms
  - robot: panda
  - scene: basic_playtable
  - env: env
  - env@eval_env: env
  - camera_conf: topview
  - test: test
  - agent: default
  - optim@optim: sac_optim
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
