save_dir: ./hydra_outputs/affordance_model/

model_name: test
n_epochs: 50
img_size:
  static: 200
  gripper: 64
  all: 100  # Resize to this if using all images

rand_crop: 0.8

dataset_name: task_A_A
dataset:
  root_dir: ${paths.datasets}/${dataset_name}
  cam: static
  n_train_ep: -1  # Train using all episodes
  radius:
    static: 14
    gripper: 10

dataloader:
  num_workers: 4
  batch_size : 128 #28
  pin_memory: True

trainer:
  gpus: -1
  max_epochs: ${n_epochs}
  num_sanity_val_steps: 1
  strategy: ddp

#-- Hydra config --#
hydra:
  run:
    dir: ${save_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S} # Output directory for normal runs

defaults:
  - paths: general_paths
  - aff_model@model_cfg: aff_model
  - transforms@dataset.transforms_cfg: aff_transforms
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
