load_dir: ???
data_path: C:/Users/Jessica/Documents/Proyecto_ssd/VREnv/data/
save_dir: ./outputs/past_env/
task: slide
model_name: sac_vrenv
repeat_training: 1

defaults:
  - agent: sac_vrpastenv
  - env: past_env
  - env@eval_env: past_env
  - eval@eval_config: eval_config
  - optim@optim: config_optim
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

static_camera:
  _target_: VREnv_past.src.camera.static_camera.StaticCamera
  fov: 75
  aspect: 1
  nearval: 0.01
  farval: 2
  width: 300
  height: 300
  look_at: [0.1, 0.8, 0.7]
  look_from: [0.3, -0.2, 1.3]

gripper_camera:
  _target_: VREnv_past.src.camera.gripper_camera.GripperCamera
  fov: 75
  aspect: 1
  nearval: 0.01
  farval: 2
  width: 300
  height: 300
  robot_id: 7
  gripper_cam_link: 12

hydra:
  run:
    dir: ${save_dir}./${now:%Y-%m-%d}/${now:%H-%M-%S}