load_dir: ???
data_path: C:/Users/Jessica/Documents/Proyecto_ssd/VREnv/data/
save_dir: ./outputs/${task}
task: slide
model_name: sac_vrenv
repeat_training: 1
img_obs: False

defaults:
  - agent: sac_default
  - env: env
  - env@eval_env: env
  - eval@eval_config: eval_config
  - scene@env.scene: basic_playtable
  - scene@eval_env.scene: basic_playtable
  - camera_conf@env: slide_drawer_camera
  - camera_conf@eval_env: slide_drawer_camera
  - optim@optim: config_optim
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

img_wrapper:
  history_length: 1
  skip_frames: 0
  img_size: 84
  
all_cameras:
  slide_hinge_camera:    
    _target_: src.camera.static_camera.StaticCamera
    name: static
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    # look_at: [ 0.16, 0.85, 0.5 ]
    # look_from: [0.2, 0.05, 1.3]
    look_at: [ 0.2, 0.8, 0.6 ]
    look_from: [0.8, 0.2, 1]
  slide_drawer_camera:    
    _target_: src.camera.static_camera.StaticCamera
    name: static
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    # look_at: [ 0.05, 0.8, 0.6 ]
    # look_from: [-0.5, 0.2, 1]
    look_at: [ 0.2, 0.85, 0.5 ]
    look_from: [0.2, 0.05, 1.3]
  static:
    _target_: src.camera.static_camera.StaticCamera
    name: static
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    look_at: [ 0.1, 0.8, 0.7 ]
    look_from: [ 0.3, -0.2, 1.3 ]

  gripper:
    _target_: src.camera.gripper_camera.GripperCamera
    name: gripper
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    gripper_cam_link: 12 # TODO do not hardcode this, use robot property? e.g. ${robot.camera_link_id}

  opposing:
    _target_: src.camera.static_camera.StaticCamera
    name: opposing
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 300
    height: 300
    look_at: [ 0.4, 0.5, 0.6 ]
    look_from: [ 0.4, 1.5, 0.9 ]

hydra:
  run:
    dir: ${save_dir}./${now:%Y-%m-%d}/${now:%H-%M-%S}