project_folder: /mnt/ssd_shared/Users/Jessica/Documents/Proyecto_ssd/Master-project/

# Load data relative to root directory
# Validation episodes
# data_dir: [../datasets/tabletop_multiscene_MoC-True/tabletop_kitchen_MoC-True/episode_10/data/gripper_cam/,
#            ../datasets/tabletop_multiscene_MoC-True/tabletop_tools_MoC-True/episode_10/data/gripper_cam/,
#            ../datasets/tabletop_multiscene_MoC-True/tabletop_misc_MoC-True/episode_10/data/gripper_cam/]

get_eval_files: False
data_dir: /mnt/ssd_shared/Users/Jessica/Documents/Proyecto_ssd/datasets/teleop_real/teleop_real_08_09/episode_05/data/static_cam/
# # Gripper camera
# folder_name: ${project_folder}/affordance_model/hydra_outputs/2021-05-30/00-41-40
# model_name: last.ckpt

# Static camera
# folder_name: ${project_folder}/affordance_model/hydra_outputs/2021-05-30/01-57-19
# model_name: static_centers_2-5_1_5_1_200px_epoch=13-val_miou=0.362.ckpt

# folder_name: ${project_folder}
# model_name: static_cam_center_preds_1.ckpt

# Multitask static
# folder_name: ${project_folder}/affordance_model/hydra_outputs/2021-07-19/01-19-28_aff_rl
# model_name: multitask_hinge_left_static_epoch=10-val_miou=0.360.ckpt

# Playtable Gripper
# folder_name: ${project_folder}/affordance_model/hydra_outputs/2021-07-19/01-14-58_aff_rl
# model_name: last.ckpt

# Tabletop multiscene Gripper
# folder_name: ${project_folder}/affordance_model/hydra_outputs/2021-07-23/15-19-34_aff_rl
# model_name: last.ckpt

# Tabletop multiscene Static cam
# folder_name: ${project_folder}/affordance_model/hydra_outputs/2021-07-25/03-03-40_aff_rl
# model_name: tabletop_multiscene_gripper_epoch=98-val_miou=0.577.ckpt

# Tabletop real-world Static cam
folder_name: ${project_folder}/affordance_model/hydra_outputs/2021-09-09/10-39-36_aff_rl
model_name: last.ckpt
cam_type: static

save_images: True
imshow: True
out_size: 300
output_dir: ${project_folder}/affordance_model/predictions/aff_static_multitask

model_cfg:
  n_classes: 2
  hough_voting:
    skip_pixels: 2
    inlier_threshold: 0.7
    angle_discretization: 100
    inlier_distance: 10
    percentage_threshold: 0.3
    object_center_kernel_radius: 10
  centers_loss:
    weight: 2.5
  aff_loss:
    weight: 1
    dice_loss:
      add: True
      weight: 5
    ce_loss:
      weight: 1
      class_weights: [0.2, 0.8]
  optimizer:
    lr: 1e-5
    weight_decay: 1e-3
  unet_cfg:
    decoder_channels: [128, 64, 32]

#-- Hydra config --#
# hydra output will be stored to save_dir
save_dir: ../../tmp/
hydra:
  run:
    dir: ${save_dir}/viz # Output directory for normal runs

defaults:
  - transforms: aff_transforms
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
