project_folder: /mnt/ssd_shared/Users/Jessica/Documents/Proyecto_ssd/Master-project/

# Load data relative to root directory
# Validation episodes
data_dir: [../datasets/hinge_left_64px/episode_5/data/gripper_cam/]
          # ../datasets/vrenv_directions_64px/episode_10/data/gripper_cam/,
          # ../Proyecto_ssd/datasets/vrenv_directions_64px/episode_13/data/gripper_cam/]

# # Gripper camera
# folder_name: ${project_folder}/affordance_model/hydra_outputs/2021-05-30/00-41-40
# model_name: last.ckpt

# Static camera
# folder_name: ${project_folder}/affordance_model/hydra_outputs/2021-05-30/01-57-19
# model_name: static_centers_2-5_1_5_1_200px_epoch=13-val_miou=0.362.ckpt

# folder_name: ${project_folder}
# model_name: static_cam_center_preds_1.ckpt

# Multitask: Static
# folder_name: ${project_folder}/affordance_model/hydra_outputs/2021-07-14/11-31-40_aff_rl
# model_name: last.ckpt

# Center
folder_name: ${project_folder}/affordance_model/hydra_outputs/2021-07-14/23-30-30_aff_rl
model_name: hinge_left_gripper_epoch=42-val_miou=0.480.ckpt

# Output img size, must be mutiple of 32
save_images: False
imshow: True
img_size: 64
out_size: 300
output_dir: ${project_folder}/affordance_model/predictions/aff_static_multitask

model_cfg:
  n_classes: 2
  hough_voting:
    skip_pixels: 2
    inlier_threshold: 0.7
    angle_discretization: 100
    inlier_distance: 10
    percentage_threshold: 0.3
    object_center_kernel_radius: 10
  centers_loss:
    weight: 2.5
  aff_loss:
    weight: 1
    dice_loss:
      add: True
      weight: 5
    ce_loss:
      weight: 1
      class_weights: [0.2, 0.8]
  optimizer:
    lr: 1e-5
    weight_decay: 1e-3
  unet_cfg:
    decoder_channels: [128, 64, 32]

#-- Hydra config --#
# hydra output will be stored to save_dir
save_dir: ../../tmp/
hydra:
  run:
    dir: ${save_dir}/viz # Output directory for normal runs

defaults:
  - transforms: aff_transforms
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
