get_eval_files: True

# Tabletop real-world Static cam
folder_name: ${paths.vapo_path}/hydra_outputs/affordance_model/2021-11-26/17-47-08_aff_rl
model_name: last.ckpt
cam_type: static
dataset_name: real_world/drawer_affordance
data_dir: "${paths.datasets}/${dataset_name}"

save_images: False
imshow: True
out_size: 200
output_dir: ${paths.vapo_path}/outputs/affordance_model/predictions/static_real_world

dataset:
  root_dir: ${paths.datasets}/${dataset_name}
  cam: ${cam_type}
  n_train_ep: -1  # Train using all episodes
  transforms_cfg: ${transforms}

dataloader:
  num_workers: 4
  batch_size : 128 #28
  pin_memory: True

img_size:
  static: 200
  gripper: 64

#-- Hydra config --#
# hydra output will be stored to save_dir
save_dir: ../../tmp/
hydra:
  run:
    dir: ${save_dir}/viz # Output directory for normal runs

defaults:
  - paths: general_paths
  - aff_model@model_cfg: aff_model
  - transforms: aff_transforms
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
