project_folder: /mnt/16867D9A9C78B590/Users/Jessica/Documents/Proyecto_ssd/SAC/affordance_model # "C:/Users/Jessica/Documents/Proyecto_ssd/SAC/affordance_model"

# Load data
# Validation episodes
data_dir: [../../Proyecto_ssd/datasets/vrenv_directions_200px/episode_0/data/static_cam/ ]
          #  ../../Proyecto_ssd/datasets/vrenv_directions_64px/episode_10/data/gripper_cam/,
          #  ../../Proyecto_ssd/datasets/vrenv_directions_64px/episode_13/data/gripper_cam/]

# gripper_1CE_5dice_miou
# folder_name:  ${project_folder}/hydra_outputs/2021-04-07/09-23-52
# model_name: affordance-epoch=121-val_miou=0.55.ckpt

# gripper_1CE_5dice_x64_miou
# folder_name:  ${project_folder}/hydra_outputs/2021-04-11/23-16-53
# model_name: affordance-epoch=113-val_miou=0.629.ckpt

# gripper_1CE_1dice_miou
# folder_name:  ${project_folder}/hydra_outputs/2021-04-07/09-24-04
# model_name: affordance-epoch=63-val_miou=0.59.ckpt

# gripper_dice_miou
# folder_name:  ${project_folder}/hydra_outputs/2021-04-07/09-24-21
# model_name: affordance-epoch=16-val_total_loss=0.47.ckpt

# gripper_CE_miou
# folder_name:  ${project_folder}/hydra_outputs/2021-04-07/09-25-36
# model_name: affordance-epoch=77-val_miou=0.58.ckpt

# gripper dice 64

folder_name:  ${project_folder}/hydra_outputs/2021-05-22/13-27-19
model_name: overfit_centers_ep0_centers5_aff200px_epoch=99-val_miou=0.801.ckpt
# gripper_aff_center_epoch=38-val_miou=0.393

# Output img size, must be mutiple of 32
save_images: False
imshow: True
img_size: 200
out_size: 300
output_dir: ${project_folder}/predictions/aff_centers_dir_static

model_cfg:
  model_name: "${model_name}"
  n_classes: 2
  hough_voting:
    skip_pixels: 2
    inlier_threshold: 0.7
    angle_discretization: 100
    inlier_distance: 10
    percentage_threshold: 0.3
    object_center_kernel_radius: 10
  centers_loss:
    weight: 3
  aff_loss:
    weight: 1
    dice_loss:
      add: True
      weight: 5
    ce_loss:
      weight: 1
      class_weights: [0.2, 0.8]
  optimizer:
    lr: 1e-5
    weight_decay: 1e-3
  unet_cfg:
    decoder_channels: [128, 64, 32]

defaults:
  - transforms: img_transforms
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

#-- Hydra config --#
save_dir: ../../tmp/
hydra:
  run:
    dir: ${save_dir}/viz # Output directory for normal runs
