project_folder: /mnt/16867D9A9C78B590/Users/Jessica/Documents/Proyecto_ssd/Master-project/ # "C:/Users/Jessica/Documents/Proyecto_ssd/SAC/"

# Load data relative to root directory
# Validation episodes
data_dir: [../datasets/tabletop_directions_64px_MoC/episode_1/data/gripper_cam/]
          # ../datasets/vrenv_directions_64px/episode_10/data/gripper_cam/,
          # ../Proyecto_ssd/datasets/vrenv_directions_64px/episode_13/data/gripper_cam/]

# Gripper camera
folder_name: ${project_folder}/affordance_model/hydra_outputs/2021-05-30/00-41-40
model_name: last.ckpt

# Output img size, must be mutiple of 32
save_images: False
imshow: True
img_size: 64
out_size: 300
output_dir: ${project_folder}/affordance_model/predictions/aff_centers_dir_gripper

model_cfg:
  hough_voting:
    skip_pixels: 2
    inlier_threshold: 0.7
    angle_discretization: 100
    inlier_distance: 10
    percentage_threshold: 0.3
    object_center_kernel_radius: 10

#-- Hydra config --#
# hydra output will be stored to save_dir
save_dir: ../../tmp/
hydra:
  run:
    dir: ${save_dir}/viz # Output directory for normal runs

defaults:
  - transforms: img_transforms
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
