defaults:
  - paths: general_paths
  - model_cfg: default
  - transforms: grayscale
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
get_eval_files: True

# load model
model_path: ./hydra_outputs/affordance_model/2022-02-01/22-05-41
model_name: last.ckpt

dataset_name: tabletop_sideview/tabletop_kitchen
data_dir: ${paths.datasets}/${dataset_name}

# For visualization
save_images: False
imshow: True
out_size: 200
output_dir: ./predictions/

# cam_data: static
# Input size to affordance model
img_size:
  static: 200
  gripper: 64

#-- Hydra config --#
# hydra output will be stored to save_dir
save_dir: ./hydra_outputs/viz/
hydra:
  run:
    dir: ${save_dir}/viz # Output directory for normal runs
