project_folder: /mnt/16867D9A9C78B590/Users/Jessica/Documents/Proyecto_ssd/Master-project/ # "C:/Users/Jessica/Documents/Proyecto_ssd/SAC/"

# Load data relative to root directory
# Validation episodes
data_dir: [../datasets/tabletop_directions_64px_MoC/episode_1/data/gripper_cam/]
          # ../datasets/vrenv_directions_64px/episode_10/data/gripper_cam/,
          # ../Proyecto_ssd/datasets/vrenv_directions_64px/episode_13/data/gripper_cam/]

# gripper_1CE_5dice_miou
# folder_name:  ${project_folder}/hydra_outputs/2021-04-07/09-23-52
# model_name: affordance-epoch=121-val_miou=0.55.ckpt

# gripper_1CE_5dice_x64_miou
# folder_name:  ${project_folder}/hydra_outputs/2021-04-11/23-16-53
# model_name: affordance-epoch=113-val_miou=0.629.ckpt

# gripper_1CE_1dice_miou
# folder_name:  ${project_folder}/hydra_outputs/2021-04-07/09-24-04
# model_name: affordance-epoch=63-val_miou=0.59.ckpt

# gripper_dice_miou
# folder_name:  ${project_folder}/hydra_outputs/2021-04-07/09-24-21
# model_name: affordance-epoch=16-val_total_loss=0.47.ckpt

# gripper_CE_miou
# folder_name:  ${project_folder}/hydra_outputs/2021-04-07/09-25-36
# model_name: affordance-epoch=77-val_miou=0.58.ckpt

# gripper dice 64
# folder_name:  ${project_folder}/hydra_outputs/2021-05-22/13-27-19
# model_name: overfit_centers_ep0_centers5_aff200px_epoch=99-val_miou=0.801.ckpt

# Static camera
# folder_name: ${project_folder}/hydra_outputs/2021-05-23/00-50-43
# folder_name: ${project_folder}/hydra_outputs/2021-05-30/01-57-19
# model_name: last.ckpt

# Gripper camera
# folder_name: ${project_folder}/hydra_outputs/2021-05-12/11-58-02
folder_name: ${project_folder}/affordance_model/hydra_outputs/2021-05-30/00-41-40
model_name: gripper_centers_2-5_1_5_1_64px_epoch=40-val_miou=0.474.ckpt

# Output img size, must be mutiple of 32
save_images: False
imshow: True
img_size: 64
out_size: 300
output_dir: ${project_folder}/affordance_model/predictions/aff_centers_dir_static

model_cfg:
  hough_voting:
    skip_pixels: 2
    inlier_threshold: 0.7
    angle_discretization: 100
    inlier_distance: 10
    percentage_threshold: 0.3
    object_center_kernel_radius: 10

#-- Hydra config --#
# hydra output will be stored to save_dir
save_dir: ../../tmp/
hydra:
  run:
    dir: ${save_dir}/viz # Output directory for normal runs

defaults:
  - transforms: img_transforms
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

