
save_dir: "./trained_models"
hyperparameters:
    gamma: 0.98
    actor_lr: 4.492e-05
    critic_lr: 0.000160
    alpha_lr:  0.000324
    alpha: auto
    tau:  0.0077
    batch_size: 227
    buffer_size: 1e6
    learning_starts: 400 #timesteps before starting updates

net_cfg:
    hidden_dim: 442
    activation: relu
    affordance: ${affordance}

learn_config:
    total_timesteps: 500000
    log_interval: 2000 #log timestep reward every log_interval steps
    max_episode_length: 200 #max episode length
    n_eval_ep: 5