# @package _group_
save_dir: "./trained_models"
hyperparameters:
    gamma: 0.99
    actor_lr: 3e-4
    critic_lr: 3e-4
    alpha_lr: 3e-4
    alpha: "auto" #"auto",
    tau: 0.005
    batch_size: 256
    buffer_size: 1e5
    learning_starts: 0 #timesteps before starting updates

net_cfg:
    hidden_dim: 256
    activation: relu
    affordance: ${affordance}

learn_config:
    total_timesteps: 100000
    log_interval: 2000 #log timestep mean_eval reward every log_interval steps
    max_episode_length: 100 #max episode length
    n_eval_ep: 5