parent_folder: /mnt/ssd_shared/Users/Jessica/Documents/Thesis_ssd
vapo_path: ${paths.parent_folder}/vapo/
vr_data: ${paths.parent_folder}/VREnv/data/

# Trained affordance models
trained_models: ${paths.vapo_path}/trained_models/

# For training affordance model
datasets: ${paths.parent_folder}/datasets/