# @package __group
train:
  - _target_: torchvision.transforms.Resize
    size: ${img_size}
  - _target_: affordance_model.utils.transforms.ScaleImageTensor
  - _target_: torchvision.transforms.Normalize
    mean: [0.5,]
    std: [0.5,]
  - _target_: affordance_model.utils.transforms.AddGaussianNoise
    mean: [0.0]
    std: [0.01]
    
validation:
  - _target_: torchvision.transforms.Resize
    size: ${img_size}
  - _target_: affordance_model.utils.transforms.ScaleImageTensor
  - _target_: torchvision.transforms.Normalize
    mean: [0,]
    std: [1,]

masks:
  - _target_: torchvision.transforms.Resize
    size: ${img_size}
  - _target_: affordance_model.utils.transforms.ThresholdMasks #Mask is between 0 and 255
    threshold: 50